const products = [
    {
        id: 1,
        title: "Wide Leg Pants Lounge Set",
        description: "ANRABESS Women 2 Piece Outfits 2025 Fall Fashion",
        image: "https://m.media-amazon.com/images/I/61mFhuYe7AL._AC_SY741_.jpg",
        link: "https://amzn.to/3O0X5sq",
        category: "clothing",
        subCategory: "pants",
        tags: ["lounge", "set", "fall", "fashion"],
        season: "all",
        material: "cotton",
        occasion: "casual",
        price: 45.99,
        gender: "women"
    },
    {
        id: 2,
        title: "Wide Leg Sweatpants",
        description: "AUTOMET Womens Wide Leg Sweatpants Baggy Lounge Travel Pants Fall Fashion Outfits 2025 Winter Clothes Joggers",
        image: "https://m.media-amazon.com/images/I/71gugs4fQDL._AC_SY741_.jpg",
        link: "https://amzn.to/4pSNKAh",
        category: "clothing",
        subCategory: "pants",
        tags: ["sweatpants", "baggy", "travel", "joggers"],
        season: "all",
        material: "cotton",
        occasion: "casual",
        price: 29.99,
        gender: "women"
    },
    {
        id: 3,
        title: "Turtleneck Tank Tops",
        description: "Zeagoo Womens Sleeveless Mock Turtleneck Tank Tops Slim Fit Stretch Ribbed Tops Casual Basic Layering Shirts",
        image: "https://m.media-amazon.com/images/I/71lLX48N1EL._AC_SX569_.jpg",
        link: "https://amzn.to/45Z4zCs",
        category: "clothing",
        subCategory: "tops",
        tags: ["turtleneck", "tank", "slim", "ribbed"],
        season: "all",
        material: "cotton",
        occasion: "casual",
        price: 19.99,
        gender: "women"
    },
    {
        id: 4,
        title: "Trench Coat",
        description: "SOMTHRON Men's Casual Trench Coat Slim Fit Notched Collar Long Jacket Overcoat Single Breasted Pea Coat wih Pockets",
        image: "https://m.media-amazon.com/images/I/71FqcvjgkNL._AC_SX679_.jpg",
        link: "https://amzn.to/49JT2Ic",
        category: "clothing",
        subCategory: "jacket",
        tags: ["trench", "coat", "slim", "notched"],
        season: "all",
        material: "cotton",
        occasion: "casual",
        price: 59.99,
        gender: "men"
    },
    {
        id: 5,
        title: "Men's Winter Jacket",
        description: "TACVASEN Men's Winter Jacket Corduroy Warm Fleece Sherpa Lined Jacket Casual Lapel Work Trucker Coat with Multi Pockets",
        image: "https://m.media-amazon.com/images/I/71ygrjVLdJL._AC_SX569_.jpg",
        link: "https://amzn.to/3ZsHNiH",
        category: "clothing",
        subCategory: "jacket",
        tags: ["winter", "corduroy", "fleece", "sherpa"],
        season: "winter",
        material: "corduroy",
        occasion: "casual",
        price: 49.99,
        gender: "men"
    },
    {
        id: 6,
        title: "G-Shock Casio Octagonal Watch",
        description: "G-Shock Casio Metal Covered Octagonal Black Resin Band Watch GM2100-1A",
        image: "https://m.media-amazon.com/images/I/812fkCn8F9L._AC_SL1500_.jpg",
        link: "https://amzn.to/4sXZYuf",
        category: "accessories",
        subCategory: "watch",
        tags: ["g-shock", "casio", "octagonal", "resin"],
        season: "all",
        material: "resin",
        occasion: "casual",
        price: 129.99,
        gender: "unisex"
    },
    {
        id: 7,
        title: "Mens Knit Polo Shirts",
        description: "COOFANDY Mens Knit Polo Shirts Short Sleeve Ribbed Textured Polo Shirt Lightweight Casual Golf Shirts Collared T Shirt",
        image: "https://m.media-amazon.com/images/I/81lXGiA3PNL._AC_SX569_.jpg",
        link: "https://amzn.to/4sXAtZT",
        category: "clothing",
        subCategory: "shirt",
        tags: ["knit", "polo", "ribbed", "golf"],
        season: "all",
        material: "cotton",
        occasion: "casual",
        price: 25.99,
        gender: "men"
    },
    {
        id: 8,
        title: "TACVASEN Men's Lightweight Bomber Jacket",
        description: "TACVASEN Men's Lightweight Casual Bomber Jacket — Spring/Fall Windbreaker with Full Zipper, Stand Collar, and Comfortable Soft Material for Everyday Wear",
        image: "https://m.media-amazon.com/images/I/71rNJdgvB1L._AC_SX679_.jpg",
        link: "https://amzn.to/49DAElE",
        category: "clothing",
        subCategory: "jacket",
        tags: ["lightweight", "bomber", "windbreaker", "casual"],
        season: "spring",
        material: "polyester",
        occasion: "casual",
        price: 35.98,
        gender: "men"
    },
    {
        id: 9,
        title: "Casio Classic Quartz Men's Watch",
        description: "Casio Classic Quartz Analog Wristwatch for Men — Everyday Casual & Timeless Design with Reliable Quartz Movement, Durable Build, and Water Resistance",
        image: "https://m.media-amazon.com/images/I/51DuIbRU7JL._AC_SX522_.jpg",
        link: "https://amzn.to/4bRiE8N",
        category: "accessories",
        subCategory: "watch",
        tags: ["quartz", "analog", "classic", "casual"],
        season: "all",
        material: "metal & resin",
        occasion: "everyday",
        price: 27.25,
        gender: "men"
    },
    {
        id: 10,
        title: "FULLRON Men's Winter Warm Scarf",
        description: "FULLRON Men's Winter Warm Scarf — Soft, Long, Cashmere-Feel Winter Neck Scarf That Keeps You Warm and Comfortable in Cold Weather",
        image: "https://m.media-amazon.com/images/I/51Z1rPNKXdL._AC_SY741_.jpg",
        link: "https://amzn.to/45we0t0",
        category: "clothing",
        subCategory: "accessory",
        tags: ["winter", "scarf", "warm", "soft", "cashmere feel"],
        season: "winter",
        material: "soft cashmere-feel fabric",
        occasion: "cold weather",
        price: 11.99,
        gender: "men"
    },
    {
        id: 11,
        title: "SISKIN Women's Ribbed Long Sleeve Pullover Sweater",
        description: "SISKIN Women's Ribbed Knit Pullover Sweater — Long Sleeve, Comfortable Fit, Stylish Casual Top Perfect for Fall & Winter Outfit Pairing",
        image: "https://m.media-amazon.com/images/I/716rrd0nH6L._AC_SY741_.jpg",
        link: "https://amzn.to/4r7fvpH",
        category: "clothing",
        subCategory: "sweater",
        tags: ["ribbed", "pullover", "long sleeve", "knit"],
        season: "all",
        material: "knit fabric",
        occasion: "casual",
        price: 36.99,
        gender: "women"
    },
    {
        id: 12,
        title: "Oversized T Shirt for Women",
        description: "Amazon Essentials Women's Lightweight Longer Length Open-Front Cardigan Sweater — Cozy long-sleeve knit cardigan with a relaxed fit and versatile style, perfect for layering in spring, fall & winter.",
        image: "https://m.media-amazon.com/images/I/61DkIsZYPOL._SY879_.jpg",
        link: "https://amzn.to/469MB0c",
        category: "clothing",
        subCategory: "cardigan",
        tags: ["lightweight", "open front", "long sleeve", "knit"],
        season: "all",
        material: "cotton blend knit",
        occasion: "casual",
        price: 4.99,
        gender: "women"
    },
    {
        id: 13,
        title: "GRECIILOOKS Oversized Shirt for Women",
        description: "GRECIILOOKS Women's Stylish Long Shirt — A trendy Korean-style button-down top featuring an oversized fit and lightweight crepe fabric. This versatile piece works perfectly as professional office wear or a relaxed casual top for daily outings.",
        image: "https://m.media-amazon.com/images/I/61dsZfNbDKL._SY879_.jpg",
        link: "https://amzn.to/45IPTYd",
        category: "clothing",
        subCategory: "shirt",
        tags: ["oversized", "korean style", "button down", "breathable", "western wear"],
        season: "all",
        material: "crepe",
        occasion: "casual / office",
        price: 4.99,
        gender: "women"
    },
    {
        id: 14,
        title: "Women's Tie-Dye Pajama Set",
        description: "SMOWKLY Relaxed Fit Sleepwear — A trendy Korean-style lounge set featuring a soft short-sleeve top and matching long pants with functional pockets. Designed for ultimate comfort, this breathable tie-dye set is ideal for both sleeping and all-day lounging.",
        image: "https://m.media-amazon.com/images/I/51lBSIuGIiL.jpg",
        link: "https://amzn.to/3ZJ4AHa",
        category: "clothing",
        subCategory: "nightwear",
        tags: ["tie-dye", "relaxed fit", "pajama set", "loungewear", "korean style"],
        season: "all",
        material: "soft cotton blend",
        occasion: "sleepwear / lounging",
        price: 7.99,
        gender: "women"
    },
    {
        id: 15,
        title: "Women's Front Open Floral Printed Shrug",
        description: "TOPLOT Lightweight Floral Shrug — A breezy, front-open layer crafted from soft chiffon. This versatile regular-fit top features a bohemian floral print, making it an ideal choice for a beach cover-up, a boho-chic outfit, or a casual layer over jeans and a tank top.",
        image: "https://m.media-amazon.com/images/I/81z2CdAtmLL._SY879_.jpg",
        link: "https://amzn.to/4c2LnHO",
        category: "clothing",
        subCategory: "shrug",
        tags: ["floral print", "front open", "chiffon", "boho vibes", "beachwear"],
        season: "summer",
        material: "chiffon / georgette",
        occasion: "casual / beach",
        price: 4.99,
        gender: "women"
    },
    {
        id: 16,
        title: "Men's Polycotton Textured Half Sleeve Shirt",
        description: "GRECIILOOKS Men's Polycotton Shirt — A stylish regular-fit textured half-sleeve shirt made from durable polycotton fabric. Comfortable enough for daily wear and polished enough for office, parties, meetings, and casual outings.",
        image: "https://m.media-amazon.com/images/I/81Z60TWdX4L._SY879_.jpg",
        link: "https://amzn.to/3LWu9kV",
        category: "clothing",
        subCategory: "shirt",
        tags: ["men shirt", "half sleeve", "textured", "polycotton", "casual wear", "office wear"],
        season: "all",
        material: "polycotton",
        occasion: "casual / office / party",
        price: 4.99,
        gender: "men"
    },
    {
        id: 17,
        title: "Men and Boys Super Oversized Embroidered Cotton T-Shirt",
        description: "Potter: The Silent Vow off-white super oversized T-shirt featuring subtle embroidery. Made from soft cotton, designed for casual streetwear comfort with a relaxed, modern fit.",
        image: "https://m.media-amazon.com/images/I/61SZDllAZjL._SY879_.jpg",
        link: "https://amzn.to/4kaOOhH",
        category: "clothing",
        subCategory: "t-shirt",
        tags: ["oversized t-shirt", "streetwear", "embroidered", "round neck", "short sleeves", "cotton"],
        season: "all",
        material: "cotton",
        occasion: "casual / streetwear",
        price: 13.99,
        gender: "men"
    },
    {
        id: 18,
        title: "Men and Boys Oversized Cotton Linen Bomber Jacket",
        description: "The Souled Store Dune lightweight bomber jacket made from a breathable cotton-linen blend. Features a solid design with full sleeves, band neck, and oversized fit, ideal for casual summer streetwear.",
        image: "https://m.media-amazon.com/images/I/51LUZGjutyL._SY879_.jpg",
        link: "https://amzn.to/4bwkQTg",
        category: "clothing",
        subCategory: "jacket",
        tags: ["bomber jacket", "cotton linen", "oversized fit", "streetwear", "lightweight", "summer wear"],
        season: "summer",
        material: "cotton linen",
        occasion: "casual / streetwear",
        price: 23.99,
        gender: "men"
    },
    {
        id: 19,
        title: "Men's Stand-Up Collar Zip-Up Sweatshirt",
        description: "PROSHARX old money aesthetic zip-up sweatshirt featuring a stand-up collar. Designed for premium comfort with a timeless, minimal look suitable for casual and smart streetwear styling.",
        image: "https://m.media-amazon.com/images/I/71PX49awLjL._SX679_.jpg",
        link: "https://amzn.to/3M8LSpb",
        category: "clothing",
        subCategory: "sweatshirt",
        tags: ["zip up sweatshirt", "stand up collar", "old money style", "minimal aesthetic", "casual wear"],
        season: "all",
        material: "cotton blend",
        occasion: "casual / streetwear",
        price: 19.99,
        gender: "men"
    },
    {
        id: 20,
        title: "Vintage Small Rectangle Metal Frame Sunglasses",
        description: "Karsaer vintage-inspired small rectangle sunglasses with a retro square metal frame. Designed for both men and women, offering a trendy unisex look suitable for everyday fashion styling.",
        image: "https://m.media-amazon.com/images/I/71qgi893hdL._SX679_.jpg",
        link: "https://amzn.to/3M8MGud",
        category: "accessories",
        subCategory: "sunglasses",
        tags: ["vintage sunglasses", "rectangle frame", "metal frame", "retro style", "unisex eyewear"],
        season: "all",
        material: "metal",
        occasion: "casual / fashion",
        price: 16.99,
        gender: "unisex"
    },
    {
        id: 21,
        title: "Vintage Rectangular Rimless Sunglasses",
        description: "IFLASH retro-style rectangular rimless sunglasses with a gold frame and grey lenses. Designed for men and women, offering a stylish vintage look for everyday fashion wear.",
        image: "https://m.media-amazon.com/images/I/61Kg4i5JwqL._SY879_.jpg",
        link: "https://amzn.to/4t9A1YC",
        category: "accessories",
        subCategory: "sunglasses",
        tags: ["vintage sunglasses", "rectangular sunglasses", "rimless", "retro style", "unisex eyewear"],
        season: "all",
        material: "metal",
        occasion: "casual / fashion",
        price: 3.99,
        gender: "unisex"
    },
    {
        id: 22,
        title: "Shasmi Women's 3-Piece Co-ord Set",
        description: "Shasmi women's western-style 3-piece co-ord set featuring a solid button-front shirt, strapless tube top, and wide-leg pants. Designed with a loose, comfortable fit, ideal for casual daily wear during spring and fall seasons.",
        image: "https://m.media-amazon.com/images/I/71O2arvsWvL._SY879_.jpg",
        link: "https://amzn.to/4qhX40V",
        category: "clothing",
        subCategory: "co-ord sets",
        tags: ["women co-ord set", "3-piece outfit", "western wear", "casual outfit", "loose fit", "spring fall wear"],
        season: "spring",
        material: "fabric",
        occasion: "casual / daily wear",
        price: 8.99,
        gender: "women"
    },
    {
        id: 23,
        title: "Symbol Premium Women's Solid Sleeveless Wrap Top",
        description: "Symbol Premium women's solid sleeveless wrap top designed in a regular fit, perfect for desk-to-dinner wear. A versatile and elegant piece suitable for office, casual outings, and evening looks. Available in inclusive plus sizes.",
        image: "https://m.media-amazon.com/images/I/71KM6xBLS7L._SY879_.jpg",
        link: "https://amzn.to/4kghcPp",
        category: "clothing",
        subCategory: "tops",
        tags: ["women wrap top", "sleeveless top", "office wear", "desk to dinner", "solid top", "plus size clothing"],
        season: "all",
        material: "fabric",
        occasion: "office / casual / evening wear",
        price: 9.99,
        gender: "women"
    },
    {
        id: 24,
        title: "Istyle Can Women's Slim Fit Solid Rib Knit Stretchable Top",
        description: "Istyle Can women's slim-fit solid rib-knit top featuring a round neck and short sleeves. Made with high-stretch, comfortable fabric, this plain fitted T-shirt is suitable for casual wear as well as office styling. Designed as a regular top for girls and women.",
        image: "https://m.media-amazon.com/images/I/61MrkcD2y3L._SX679_.jpg",
        link: "https://amzn.to/4qTY10h",
        category: "clothing",
        subCategory: "tops",
        tags: ["women slim fit top", "rib knit top", "stretchable t-shirt", "round neck tee", "office casual wear", "plain fitted top"],
        season: "all",
        material: "rib knit fabric",
        occasion: "casual / office wear",
        price: 2.99,
        gender: "women"
    },
    {
        id: 25,
        title: "Women's Long Sleeve Bow Tie Neck Chiffon Blouse",
        description: "Elegant women's long-sleeve blouse crafted from lightweight chiffon fabric, featuring a bow-tie neck and V-neck design. Styled in a relaxed Korean-inspired fit, this blouse is ideal for polished office wear and sophisticated everyday looks. Available in pink and white color options.",
        image: "https://m.media-amazon.com/images/I/51HyyoAsG2L.jpg",
        link: "https://amzn.to/4byZ7Kk",
        category: "clothing",
        subCategory: "blouses",
        tags: ["women chiffon blouse", "bow tie neck top", "korean style blouse", "office wear shirt", "elegant women top", "long sleeve blouse"],
        season: "all",
        material: "chiffon",
        occasion: "office / formal / casual",
        price: 4.99,
        gender: "women"
    },
    {
        id: 26,
        title: "Butterfly Metal Hair Clip",
        description: "Stylish butterfly-shaped metal hair clip designed for women and girls. Durable claw clip construction provides a secure hold while adding an elegant and trendy touch to everyday hairstyles.",
        image: "https://m.media-amazon.com/images/I/51kSNS4AOnL.jpg",
        link: "https://amzn.to/3ZJKg8C",
        category: "accessories",
        subCategory: "hair accessories",
        tags: ["butterfly hair clip", "metal hair clip", "claw clip", "hair accessories for women", "hair accessories for girls"],
        season: "all",
        material: "metal",
        occasion: "casual / daily wear",
        price: 1.99,
        gender: "women"
    },
    {
        id: 27,
        title: "Sugathari Women's Elegant High Neck Bow Detail Tank Top",
        description: "Chic sleeveless ribbed tank top featuring a high neckline and elegant bow detail. Designed in a soft beige shade, this stylish blouse offers a flattering fit, making it perfect for summer casual outings, daily wear, or pairing with jeans and skirts for a trendy look.",
        image: "https://m.media-amazon.com/images/I/81htP4KDPjL._SY879_.jpg",
        link: "https://amzn.to/4kLf3M6",
        category: "clothing",
        subCategory: "tops",
        tags: ["women tank top", "high neck top", "bow detail blouse", "ribbed sleeveless top", "summer fashion top", "beige stylish top"],
        season: "summer",
        material: "ribbed fabric",
        occasion: "casual / daily wear",
        price: 3.99,
        gender: "women"
    },
    {
        id: 28,
        title: "GRECIILOOKS Women High Rise High Waist Flared Korean Style Trousers",
        description: "Elegant high-rise, high-waist flared trousers inspired by Korean fashion. Designed for a flattering silhouette with a structured fit, these formal pants are perfect for office wear, college, business meetings, and special events. Stylish yet comfortable, they pair effortlessly with tops, blouses, and blazers for a polished look.",
        image: "https://m.media-amazon.com/images/I/71u+frPwGpL._SY879_.jpg",
        link: "https://amzn.to/46gPCMj",
        category: "clothing",
        subCategory: "trousers",
        tags: ["women formal trousers", "high waist pants", "flared trousers women", "korean style pants", "office wear women", "elegant workwear pants"],
        season: "all",
        material: "polyester blend",
        occasion: "formal / office / events",
        price: 5.99,
        gender: "women"
    },
    {
        id: 29,
        title: "Shoetopia Women Pump Heels",
        description: "Elegant women’s pump heels designed for a sleek and sophisticated look. Featuring a comfortable fit and stylish silhouette, these heels are perfect for office wear, parties, formal events, and special occasions. Pairs beautifully with dresses, skirts, and formal outfits.",
        image: "https://m.media-amazon.com/images/I/51nlyKThF2L._SY695_.jpg",
        link: "https://amzn.to/4s2HtUk",
        category: "footwear",
        subCategory: "heels",
        tags: ["women pump heels", "formal heels", "party heels", "office wear heels", "stylish high heels"],
        season: "all",
        material: "synthetic",
        occasion: "formal / party / office",
        price: 6.99,
        gender: "women"
    },
    {
        id: 30,
        title: "Women’s Solid Asymmetric Hem Stretchable Draped Crop Top",
        description: "Trendy solid crop top featuring an asymmetric hem and stretchable draped fabric for a flattering fit. Designed with a stylish single-shoulder/off-shoulder silhouette and elegant cowl neckline, this sleeveless top adds a bold and modern touch to party, casual, and evening outfits.",
        image: "https://m.media-amazon.com/images/I/61DUsfRzYDL._SY879_.jpg",
        link: "https://amzn.to/4rpzfWa",
        category: "clothing",
        subCategory: "tops",
        tags: ["asymmetric crop top", "one shoulder top women", "off shoulder crop top", "cowl neck top", "party wear crop top", "stretchable women top"],
        season: "summer",
        material: "stretchable fabric blend",
        occasion: "party / casual / evening wear",
        price: 1.99,
        gender: "women"
    },
    {
        id: 31,
        title: "ALYNE Women’s Classic Stretchy Flared Skater Skirt",
        description: "Classic stretchy flared skater skirt with a flattering fit. Perfect for casual, college, and everyday stylish looks.",
        image: "https://m.media-amazon.com/images/I/51ZhbqJinoL.jpg",
        link: "https://amzn.to/4kIp5NT",
        category: "clothing",
        subCategory: "skirts",
        tags: ["skater skirt", "flared skirt women", "stretchy skirt", "casual skirt", "college wear skirt"],
        season: "all",
        material: "stretchable fabric blend",
        occasion: "casual / daily wear",
        price: 2.99,
        gender: "women"
    },
    {
        id: 32,
        title: "SilverArrow Women’s Twilight Drift Block Heel Sandals",
        description: "Stylish block heel sandals with a chic toe-strap design. Perfect for casual outings, outdoor wear, and party looks.",
        image: "https://m.media-amazon.com/images/I/51FjsLeIjsL._SY695_.jpg",
        link: "https://amzn.to/46ckFZQ",
        category: "footwear",
        subCategory: "sandals",
        tags: ["block heel sandals", "women fashion sandals", "toe strap heels", "party sandals", "casual heel sandals"],
        season: "all",
        material: "synthetic",
        occasion: "casual / outdoor / party",
        price: 4.99,
        gender: "women"
    },
    {
        id: 33,
        title: "Winter Fuzzy Knit Leg Warmers for Women (42CM, White)",
        description: "Soft fuzzy knit leg warmers designed for skirts and Korean-style outfits. Warm, cozy, and perfect for winter layering.",
        image: "https://m.media-amazon.com/images/I/61Vcuor703L._SX679_.jpg",
        link: "https://amzn.to/3MIRhDE",
        category: "accessories",
        subCategory: "leg warmers",
        tags: ["winter leg warmers", "fuzzy knit socks", "korean outfit stockings", "skirt leg warmers", "white leg warmers women"],
        season: "winter",
        material: "knit fabric",
        occasion: "casual / winter wear",
        price: 2.99,
        gender: "women"
    },
    {
        id: 34,
        title: "Shoetopia Women’s Chunky Combat Boots",
        description: "Lace-up ankle boots with a thick lug sole and durable faux leather finish. Perfect for casual, street-style, and outdoor wear.",
        image: "https://m.media-amazon.com/images/I/51RgMAv1M7L._SY625_.jpg",
        link: "https://amzn.to/4rZakbY",
        category: "footwear",
        subCategory: "boots",
        tags: ["chunky combat boots", "lace up ankle boots", "lug sole boots women", "faux leather boots", "casual fashion boots"],
        season: "all",
        material: "faux leather",
        occasion: "casual / outdoor",
        price: 7.99,
        gender: "women"
    },
    {
        id: 35,
        title: "Theater Sheer Stockings for Women",
        description: "Comfortable, breathable sheer stockings made from nylon-spandex blend. Free size and perfect for formal or everyday wear.",
        image: "https://m.media-amazon.com/images/I/618wZeGfqpL._SX679_.jpg",
        link: "https://amzn.to/4tRjKrV",
        category: "accessories",
        subCategory: "stockings",
        tags: ["sheer stockings", "nylon spandex stockings", "women hosiery", "formal stockings", "free size stockings"],
        season: "all",
        material: "nylon spandex",
        occasion: "formal / daily wear",
        price: 3.99,
        gender: "women"
    },
    {
        id: 36,
        title: "DIMPY GARMENTS Elasticated Side Slit Mini Skirt",
        description: "Trendy elasticated mini skirt with a stylish side slit. Comfortable fit, perfect for casual and college wear.",
        image: "https://m.media-amazon.com/images/I/61dOhyUJjLL._SY879_.jpg",
        link: "https://amzn.to/3OoPTH1",
        category: "clothing",
        subCategory: "skirts",
        tags: ["mini skirt", "side slit skirt", "short skirt women", "elastic waist skirt", "casual skirt"],
        season: "all",
        material: "fabric blend",
        occasion: "casual / college wear",
        price: 2.99,
        gender: "women"
    },
    {
        id: 37,
        title: "Women’s Winter High Neck Slim Fit Thermal Top",
        description: "Soft, stretchable full-sleeve high neck top designed for winter layering. Slim fit, warm, and comfortable without fleece bulk.",
        image: "https://m.media-amazon.com/images/I/5179XrMULmL._SY879_.jpg",
        link: "https://amzn.to/4aNWrqi",
        category: "clothing",
        subCategory: "tops",
        tags: ["winter thermal top", "high neck inner top", "slim fit winter top", "full sleeve base layer", "women winter layering"],
        season: "winter",
        material: "stretchable fabric blend",
        occasion: "winter / daily wear",
        price: 4.99,
        gender: "women"
    },
    {
        id: 38,
        title: "GRECIILOOKS Women’s Oversized Zipper Hoodie",
        description: "Stylish cotton oversized hoodie with zipper closure. Comfortable, trendy, and perfect for summer or winter layering.",
        image: "https://m.media-amazon.com/images/I/71w7KslnTqL._SY879_.jpg",
        link: "https://amzn.to/4rrod2U",
        category: "clothing",
        subCategory: "hoodies",
        tags: ["oversized hoodie women", "zipper hoodie", "cotton hoodie", "casual hoodie", "women streetwear hoodie"],
        season: "all",
        material: "cotton",
        occasion: "casual / daily wear",
        price: 5.99,
        gender: "women"
    },
    {
        id: 39,
        title: "Leriya Fashion Men's Lycra Blend Regular Fit Polo T-Shirt",
        description: "Comfortable and versatile regular fit polo t-shirt made from soft lycra blend fabric. Breathable, stretchable, and perfect for daily wear. Available in plus sizes and combo packs.",
        image: "https://m.media-amazon.com/images/I/81vpSe3xzpL._SY879_.jpg",
        link: "https://amzn.to/4u4m6DU",
        category: "clothing",
        subCategory: "tshirts",
        tags: ["men polo t-shirt", "lycra blend t-shirt", "regular fit polo", "plain polo t-shirt", "plus size polo t-shirt"],
        season: "all",
        material: "lycra blend",
        occasion: "casual / daily wear",
        price: 4.99,
        gender: "men"
    }, {
        id: 40,
        title: "AVANOVA Men's Beige Slant Pocket Straight Leg Casual Pant (Trouser 260)",
        description: "Loose fit straight leg beige trousers made from a comfortable cotton blend fabric. Features slant pockets and adjustable drawstring waist, ideal for travel, outdoor activities, and casual daily wear.",
        image: "https://m.media-amazon.com/images/I/7159UJ-c1fL._SY879_.jpg",
        link: "https://amzn.to/40nKen7",
        category: "clothing",
        subCategory: "pants",
        tags: ["men beige pants", "harem style trousers", "drawstring waist pants", "travel pants men", "loose fit cotton trousers"],
        season: "all",
        material: "cotton blend",
        occasion: "casual / travel / outdoor",
        price: 7.99,
        gender: "men"
    },
    {
        id: 41,
        title: "Cruiser Men's Casual Shoes Blaze",
        description: "Comfortable and trendy classic sneakers designed for everyday casual wear. Lightweight, stylish, and perfect for relaxed outings, college, or daily use.",
        image: "https://m.media-amazon.com/images/I/71Xag1O3QBL._SY695_.jpg",
        link: "https://amzn.to/4aT8PW2",
        category: "footwear",
        subCategory: "sneakers",
        tags: ["men casual shoes", "classic sneakers", "comfortable trainers", "trendy sneakers men", "everyday casual shoes"],
        season: "all",
        material: "synthetic / textile blend",
        occasion: "casual / daily wear",
        price: 8.99,
        gender: "men"
    },
    {
        id: 42,
        title: "Shocknshop Silver Stainless Steel Analog Square Dial Watch - PGNI85",
        description: "Elegant silver stainless steel analog wrist watch featuring a modern square dial and date display. Durable build with a sleek finish, ideal for formal and casual occasions.",
        image: "https://m.media-amazon.com/images/I/61CFnDohk3L._SX679_.jpg",
        link: "https://amzn.to/4asxcL6",
        category: "accessories",
        subCategory: "watches",
        tags: ["men square dial watch", "stainless steel watch", "analog date watch", "silver wrist watch men", "formal watch men"],
        season: "all",
        material: "stainless steel",
        occasion: "formal / casual",
        price: 4.99,
        gender: "men"
    },
    {
        id: 43,
        title: "GRECIILOOKS Men's Half Sleeve Polo Neck T-Shirt",
        description: "Stylish and comfortable polo neck t-shirt designed for everyday wear. Made from breathable fabric with a regular fit, perfect for casual outings, office wear, or daily use. Available in plus sizes.",
        image: "https://m.media-amazon.com/images/I/51QXTzEBzmL.jpg",
        link: "https://amzn.to/4b40Gz2",
        category: "clothing",
        subCategory: "tshirts",
        tags: ["men polo t-shirt", "half sleeve polo tshirt", "casual polo tshirt men", "plus size polo tshirt", "mens streetwear tshirt"],
        season: "all",
        material: "cotton blend",
        occasion: "casual / daily wear",
        price: 3.99,
        gender: "men"
    },
    {
        id: 44,
        title: "Mack Jonney Regular Trouser Loose Fit Track Pant - MACK640418",
        description: "Stylish loose fit sports track pant designed for comfort and everyday movement. Ideal for workouts, travel, or casual wear, offering breathable fabric and relaxed fit.",
        image: "https://m.media-amazon.com/images/I/414NoB-6AcL.jpg",
        link: "https://amzn.to/4rtJXuJ",
        category: "clothing",
        subCategory: "trackpants",
        tags: ["men track pant", "loose fit sports trouser", "gym track pant men", "casual sportswear", "comfortable joggers men"],
        season: "all",
        material: "polyester blend",
        occasion: "sports / casual / travel",
        price: 3.99,
        gender: "men"
    },
    {
        id: 45,
        title: "Centrino Casual Lace-Up Sneakers for Men (3322)",
        description: "Stylish lace-up casual sneakers featuring a cushioned insole for enhanced comfort. Designed with a rounded front and anti-skid sole, making them ideal for walking, daily wear, and casual outings.",
        image: "https://m.media-amazon.com/images/I/71dlxS7UBWS._SY695_.jpg",
        link: "https://amzn.to/4tPFlko",
        category: "footwear",
        subCategory: "sneakers",
        tags: ["men casual sneakers", "lace up sneakers men", "comfortable walking shoes", "anti skid sole shoes", "cushioned insole sneakers"],
        season: "all",
        material: "synthetic / textile blend",
        occasion: "casual / daily wear / walking",
        price: 8.99,
        gender: "men"
    },
    {
        id: 46,
        title: "SKMEI Men's Analog Luxury Waterproof Quartz Round Dial Watch",
        description: "Premium stainless steel analog quartz watch featuring a geometric round dial with calendar and week display. Water resistant design with a stylish, all-in-one luxury finish suitable for both formal and casual wear.",
        image: "https://m.media-amazon.com/images/I/41KKXwjaY1L.jpg",
        link: "https://amzn.to/4c3J9YQ",
        category: "accessories",
        subCategory: "watches",
        tags: ["men luxury watch", "waterproof quartz watch", "stainless steel watch men", "round dial analog watch", "calendar week display watch"],
        season: "all",
        material: "stainless steel",
        occasion: "formal / casual",
        price: 18.99,
        gender: "men"
    },
    {
        "id": 47,
        "title": "CB-COLEBROOK Men's Long Sleeve Button Down Casual Cotton Linen Shirt",
        "description": "Lightweight and breathable long-sleeve button down shirt made from breathable cotton-linen blend. Perfect for summer beach days, casual outings, or relaxed everyday wear — available in regular and plus sizes for a comfortable fit.",
        "image": "https://m.media-amazon.com/images/I/71kfgknfIsL._SY879_.jpg",
        "link": "https://amzn.to/4rtoK49",
        "category": "clothing",
        "subCategory": "shirts",
        "tags": [
            "men casual shirt",
            "button down linen shirt",
            "summer beach shirt",
            "long sleeve men shirt",
            "plus size men's top"
        ],
        "season": "summer",
        "material": "cotton linen blend",
        "occasion": "casual / beach",
        "price": 7.99,
        "gender": "men"
    },
    {
        "id": 48,
        "title": "Relaxed-fit corduroy sweatpants",
        "description": "Sweatpants with a stretchable elastic waistband and adjustable drawstring. Designed for all-day comfort, casual wear, gym sessions, or winter lounging with a premium yet flexible feel.",
        "image": "https://m.media-amazon.com/images/I/416KAVsRGwL.jpg",
        "link": "https://amzn.to/4c68i5f",
        "category": "clothing",
        "subCategory": "pants",
        "tags": [
            "men sweatpants",
            "corduroy joggers",
            "stretch waist sweatpant",
            "casual gym joggers",
            "winter wear trousers"
        ],
        "season": "winter",
        "material": "corduroy / cotton blend",
        "occasion": "casual / gym",
        "price": 4.99,
        "gender": "men"
    },
    {
        "id": 49,
        "title": "Casual mid-top sneaker shoes",
        "description": "Casual mid-top sneaker shoes featuring a synthetic upper and PVC outsole with lace-up closure. Lightweight and comfortable for daily casual wear, offering relaxed style and supportive fit suitable for men and boys.",
        "image": "https://m.media-amazon.com/images/I/81R6YbNKOzL._SY695_.jpg",
        "link": "https://amzn.to/3ZTDP2Z",
        "category": "footwear",
        "subCategory": "sneakers",
        "tags": [
            "men casual sneakers",
            "mid top sneaker shoes",
            "synthetic upper shoes",
            "lightweight comfortable shoes",
            "lace up sneaker"
        ],
        "season": "all",
        "material": "synthetic / PVC",
        "occasion": "casual",
        "price": 7.99,
        "gender": "men"
    },
    {
        "id": 50,
        "title": "TIMEWORKS Stainless Steel Designer Golden Round Shape Day & Date Analog Watch",
        "description": "Elegant golden round shape analog watch featuring a stainless steel strap with day and date display. Designed with a premium metallic finish, suitable for both men and boys for formal and casual occasions.",
        "image": "https://m.media-amazon.com/images/I/81TlAgJIxLL._SX679_.jpg",
        "link": "https://amzn.to/3OymA4M",
        "category": "accessories",
        "subCategory": "watches",
        "tags": [
            "golden analog watch",
            "stainless steel watch",
            "day date dial watch",
            "men designer watch",
            "round shape watch"
        ],
        "season": "all",
        "material": "stainless steel",
        "occasion": "formal / casual",
        "price": 3.99,
        "gender": "men"
    },
    {
        "id": 51,
        "title": "Eyewearlabs OKNO Polarized Full Rim Alloy Square Stylish Sunglasses",
        "description": "Polarized full-rim alloy sunglasses with square frame and 100% UV protection. Stylish and durable shades suitable for men and women, perfect for cricket, sports, cycling, driving, and everyday outdoor wear.",
        "image": "https://m.media-amazon.com/images/I/51sbgMetKzL._SX679_.jpg",
        "link": "https://amzn.to/4kSWOUT",
        "category": "accessories",
        "subCategory": "sunglasses",
        "tags": [
            "polarized sunglasses",
            "full rim alloy shades",
            "UV protection eyewear",
            "unisex sunglasses",
            "sports driving cycling glasses"
        ],
        "season": "all",
        "material": "alloy",
        "occasion": "sports / casual",
        "price": 19.99,
        "gender": "unisex"
    },
    {
        "id": 52,
        "title": "London Hills Women’s Solid Ribbed Long Sleeve Slim Fit T-Shirt",
        "description": "Stretchable ribbed long sleeve slim fit t-shirt with a comfortable round neck, perfect for casual everyday wear. Designed for a flattering fit and soft feel.",
        "image": "https://m.media-amazon.com/images/I/510ZaGeYBOL.jpg",
        "link": "https://amzn.to/3OEExyA",
        "category": "clothing",
        "subCategory": "tops",
        "tags": [
            "women t shirt",
            "ribbed long sleeve top",
            "slim fit tee",
            "stretchable round neck",
            "casual women shirt"
        ],
        "season": "all",
        "material": "ribbed knit",
        "occasion": "casual",
        "price": 2.99,
        "gender": "women"
    },
    {
        "id": 53,
        "title": "London Hills Women's Relaxed Fit High Rise Baggy Jeans",
        "description": "Relaxed fit high-rise women's jeans with a loose, oversized baggy style perfect for casual everyday wear. Comfortable denim with a contemporary relaxed silhouette.",
        "image": "https://m.media-amazon.com/images/I/81MuoEzDncL._SY879_.jpg",
        "link": "https://amzn.to/4b5K3mw",
        "category": "clothing",
        "subCategory": "jeans",
        "tags": [
            "women baggy jeans",
            "high rise relaxed fit",
            "loose oversized jeans",
            "casual women denim",
            "London Hills jeans"
        ],
        "season": "all",
        "material": "denim",
        "occasion": "casual",
        "price": 6.99,
        "gender": "women"
    },
    {
        "id": 54,
        "title": "Campus Women Raise Sneakers",
        "description": "Casual women’s sneakers with a comfortable fit and stylish design, ideal for daily wear, walking, sports, and casual outings.",
        "image": "https://m.media-amazon.com/images/I/61KNZZkCjYL._SY625_.jpg",
        "link": "https://amzn.to/4kOor1z",
        "category": "footwear",
        "subCategory": "sneakers",
        "tags": [
            "women sneakers",
            "Campus Raise shoes",
            "casual footwear",
            "comfortable sneakers",
            "everyday shoes"
        ],
        "season": "all",
        "material": "synthetic / fabric",
        "occasion": "casual",
        "price": 9.99,
        "gender": "women"
    },
    {
        "id": 55,
        "title": "LEOTUDE Men's Half Sleeve Round Neck Cottonblend Graphic Print Oversized Tshirt",
        "description": "Trendy oversized men’s t-shirt made from soft cotton blend fabric, featuring a stylish graphic print. Designed with a round neck and half sleeves, perfect for casual wear, street style, college outfits, and everyday comfort.",
        "image": "https://m.media-amazon.com/images/I/61WYx598KKL._SY879_.jpg",
        "link": "https://amzn.to/4aAKw05",
        "category": "clothing",
        "subCategory": "tshirts",
        "tags": [
            "men oversized tshirt",
            "graphic print tshirt",
            "cotton blend tshirt",
            "casual men wear",
            "street style tshirt",
            "round neck tshirt"
        ],
        "season": "all",
        "material": "cotton blend",
        "occasion": "casual",
        "price": 2.99,
        "gender": "men"
    },
    {
        "id": 56,
        "title": "Ben Martin Men Baggy Fit High Rise Denim Jeans",
        "description": "Stylish baggy fit men’s jeans made from stretchable denim cotton fabric. Designed with a high-rise waist and loose fit silhouette, perfect for casual wear, street style, dance, rap, and everyday comfort. Durable material with a relaxed vibe for modern urban fashion.",
        "image": "https://m.media-amazon.com/images/I/71tq2wDUoRL._SY879_.jpg",
        "link": "https://amzn.to/4qPRfrT",
        "category": "clothing",
        "subCategory": "jeans",
        "tags": [
            "men baggy jeans",
            "loose fit denim",
            "high rise jeans",
            "stretchable jeans",
            "street style jeans",
            "rap style pants"
        ],
        "season": "all",
        "material": "denim cotton",
        "occasion": "casual",
        "price": 8.99,
        "gender": "men"
    },
    {
        "id": 57,
        "title": "ASIAN Men's White Casual Sneaker Shoes with Synthetic Upper Lightweight Comfortable Mid Top Sneaker Shoes for Men's & Boy's Boston-01",
        "description": "Classic white casual sneakers for men and boys featuring a synthetic upper and lightweight mid-top design. Comfortable and versatile, ideal for daily wear, casual outings, and all-day comfort.",
        "image": "https://m.media-amazon.com/images/I/71Oay2CuquL._SY695_.jpg",
        "link": "https://amzn.to/4ayiVMZ",
        "category": "footwear",
        "subCategory": "sneakers",
        "tags": [
            "men white sneakers",
            "ASIAN casual shoes",
            "lightweight sneakers",
            "comfortable footwear",
            "mid top sneakers"
        ],
        "season": "all",
        "material": "synthetic",
        "occasion": "casual",
        "price": 6.99,
        "gender": "men"
    },
    {
        "id": 58,
        "title": "Nakabh Stainless Steel Statement Necklace Chain for Boys & Men",
        "description": "Minimal stainless steel chain with a bold, elegant look. Durable, stylish, and perfect for daily or party wear.",
        "image": "https://m.media-amazon.com/images/I/61LqJhGpcJL._SY695_.jpg",
        "link": "https://amzn.to/4b89e84",
        "category": "accessories",
        "subCategory": "necklaces",
        "tags": [
            "men chain",
            "stainless steel necklace",
            "statement chain",
            "boys jewelry",
            "fashion accessories"
        ],
        "season": "all",
        "material": "stainless steel",
        "occasion": "casual",
        "price": 1.99,
        "gender": "men"
    },
    {
        "id": 59,
        "title": "Grey Jack Polarized Polygon Sunglasses for Men & Women",
        "description": "Stylish polygon-shaped sunglasses with a metal frame and polarized lenses for clear vision and UV protection.",
        "image": "https://m.media-amazon.com/images/I/41m6ZXLxIlL._SX679_.jpg",
        "link": "https://amzn.to/4b89xQg",
        "category": "accessories",
        "subCategory": "sunglasses",
        "tags": [
            "polarized sunglasses",
            "metal frame shades",
            "unisex eyewear",
            "UV protection",
            "stylish sunglasses"
        ],
        "season": "all",
        "material": "metal frame",
        "occasion": "casual",
        "price": 12.99,
        "gender": "unisex"
    },
    {
        "id": 60,
        "title": "KZULLY Women’s Skirts",
        "description": "Stylish women’s skirts perfect for casual, party, or everyday wear.",
        "image": "https://m.media-amazon.com/images/I/611n63LBJJL._SY879_.jpg",
        "link": "https://amzn.to/4azQPkp",
        "category": "clothing",
        "subCategory": "skirts",
        "tags": [
            "women skirts",
            "fashion skirts",
            "casual wear",
            "everyday skirt",
            "stylish women skirt"
        ],
        "season": "all",
        "material": "fabric",
        "occasion": "casual",
        "price": 3.99,
        "gender": "women"
    },
    {
        "id": 61,
        "title": "Puma Smash V1 Women’s Sneakers",
        "description": "Classic women’s sneakers with a low-top silhouette and SoftFoam cushioning for everyday comfort and casual wear. Sleek lace-up design and reliable rubber outsole for daily use. :contentReference[oaicite:1]{index=1}",
        "image": "https://m.media-amazon.com/images/I/41t8Xx1oJAL._SY695_.jpg",
        "link": "https://amzn.to/3OYimDA",
        "category": "footwear",
        "subCategory": "sneakers",
        "tags": [
            "women sneakers",
            "Puma Smash V1",
            "SoftFoam comfort",
            "casual shoes",
            "everyday wear"
        ],
        "season": "all",
        "material": "synthetic",
        "occasion": "casual",
        "price": 36.99,
        "gender": "women"
    }

];

const creators = [
    { id: 1, name: "Noire", handle: "@noirecore", avatar: "Noire.jpg", verified: true }
];

const outfitSets = [
    {
        id: "set-1",
        title: "Minimal Street Vibes",
        creatorId: 1,
        image: "https://i.pinimg.com/736x/8e/3c/6e/8e3c6e4e1a6a6a6a6a6a6a6a6a6a6a6a.jpg",
        products: [17, 2, 21], // T-shirt, Sweatpants, Sunglasses
        tags: ["#minimal", "#streetwear", "#essentials"]
    },
    {
        id: "set-2",
        title: "Clean Office Look",
        creatorId: 1,
        image: "https://i.pinimg.com/736x/f5/0a/7b/f50a7b1a6a6a6a6a6a6a6a6a6a6a6a6a.jpg",
        products: [13, 28, 29, 6], // Shirt, Trousers, Heels, Watch
        tags: ["#korean", "#minimal", "#workwear"]
    }
];

// Assign Noire to all products for the feed
products.forEach((p) => {
    p.creatorId = 1;
    p.tags = p.tags || [];
    if (p.category === 'clothing') p.tags.push('#fitcheck');
});
